[build]
  command = "pip install -r requirements.txt && python -c 'import pygbag; print(pygbag.__version__)"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


