[build]
  command = "pip install -r requirements.txt && python -m pygbag --archive --ume_block 0 --cdn --width 1400 --height 800 --name STMS STMS.py"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200




